### ISSUE TITLE
Improve Brushing in new Heat Map

### ISSUE THREAD

**Issue by alexsb** [Caleydo/caleydo#1526]
Love the new heatmap, Selecting works nice. 

We could add a brush that lets you select an area similar to this:

![selection](https://f.cloud.github.com/assets/2039375/919282/2661194c-fec6-11e2-8c70-fe1c7a2376fa.png)

Instead of using solid areas (which obscure the color coding) I'd stick with frames though.

**Comment by sgratzl** [comment]
I implemented some brushing: 
- drag -> select range
- CTRL-click -> add to selection
- normal click -> set selection

however, we may really need to switch to solid areas as both options (frame around every item, or frame around block (enable just the one if in SelectionManager line 57)) doesn't really work

**Comment by alexsb** [comment]
Cool!

I think we can make the outline work. I really do want to avoid coloring the area, since this ruins the data representation. I disabled the stippling for dimensions, which definitely improves things, but I agree it's still not very nice. 

A couple of ideas (not curated for sanity):
- make intersection of dimension and record selection stand out more (shadow around the frame, thicker frame, spacing to the rest).
- change mapping color for the selected area. We could keep the red-blue mapping for the selected area while switching the rest to b/w (I know we'd loose the difference between red and blue) or to some other mapping (which might look weird)

**Comment by alexsb** [comment]
Other ideas for the heat map: 
- we maybe want to enable selecting just rows or just columns. I think it would be best to add a space at all sides (or only at the right and at the  bottom) where we can brush just the columns or just the rows. This space could also be used for continuous highlighting and could be used for labels at a higher resolution. 
- Would be interesting to be able to say "show me just the selection", thus enabling zooming.

**Comment by sgratzl** [comment]
> for labels at a higher resolution. 

just set setShowLabels(...) to enable rendering of labels, similar to the original heat map

up to now the labels aren't selectable but I will implement it soon. 

> change mapping color for the selected area. We could keep the red-blue mapping for the selected area while switching the rest to b/w (I know we'd loose the difference between red and blue) or to some other mapping (which might look weird) 

that will be difficult to communicate as the color mapping can be changed, and the color mapping strategy itself is extracted to a IBlockColorer interface.

**Comment by sgratzl** [comment]
another problem with the current selection visualization is that is doesn't work when the heatmap is overplotted.

**Comment by sgratzl** [comment]
blur not selected out is the current strategy
