### ISSUE TITLE
heavy CPU load when adding mutations/CNV to TourGuide database

### ISSUE THREAD

**Issue by ngehlenborg** [Caleydo/caleydo#925]
I get CPU loads of over 300% lasting for several minutes (so far I have never seen them go down again but maybe I am too impatient). I can no longer close Caleydo and have to kill it.

To reproduce: 

(1) add mRNA clustering result to StratomeX
(2) add mutations to Tour Guide
(3) add a random gene to StratomeX
(4) add copy number to Tour Guide
(5) query for all groups in mRNA clustering

**Comment by sgratzl** [comment]
regarding tour guide: I can't reproduce this up to now, as under my test mac the scenario computes in 2-3sec

the never ending closing seems to be because of the fsp animator, when we try to remove the disposed glcanvas widget. 

r5693 stops the animator at the beginning of the shutdown process, which should solve the problem

-> please test

**Comment by ngehlenborg** [comment]
I still can't close Caleydo but maybe this is independent of the TourGuide. 

The CPU loads do go back to "normal" after TourGuide operations, so that is fixed. I think that some of the high loads are also due to an increased number (5-7) of columns (which is much easier to achieve with the TourGuide than before).

**Comment by sgratzl** [comment]
Replying to [comment:2 gehlenborg]:

> I still can't close Caleydo but maybe this is independent of the TourGuide. 
> can I have the log and the eclipse output, respectively: what is the last message in the eclipse console, when you try to close caleydo?

**Comment by sgratzl** [comment]
see also #974

r5697 ->  ProgressMonitorDialog for saving project and saving recent project

**Comment by ngehlenborg** [comment]
Last output before closing (pre-progess monitor version):
{{{
!ENTRY org.caleydo.core 1 0 2012-12-19 09:53:13.237
!MESSAGE Stop animator

!ENTRY org.caleydo.core.serialize.ProjectManager 1 0 2012-12-19 09:53:14.236
!MESSAGE saving plugin data

!ENTRY org.caleydo.core.serialize.ProjectManager 1 0 2012-12-19 09:53:14.252
!MESSAGE saving data
}}}

**Comment by sgratzl** [comment]
-> related to persisting project due to the tableperspectives created for mutations and copy numbers

-> not related to tour guide
